# docker-compose.dev.yml
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app # monta el código en vivo
    ports:
      - "8000:8000"
    env_file: .env
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/src:/app/src # solo src para no pisar node_modules del contenedor
    ports:
      - "3000:3000"
    env_file: .env
    command: pnpm dev --host
