events {}

http {
  upstream api {
    server api:8000;
  }

  upstream web {
    server web:3000;
  }

  server {
    listen 80;

    # Todo lo que empiece con /api/ va al backend
    location /api/ {
      proxy_pass http://api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Todo lo demás va al frontend
    location / {
      proxy_pass http://web;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
