FROM python:3.12-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./ 

#instala dependencias
RUN uv sync --frozen --no-install-project --no-dev

COPY app/ ./app/

ENV STORAGE_PATH=/data/docs

RUN mkdir -p /data/docs

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
